---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# themeBCR

<!-- badges: start -->
<!-- badges: end -->

The goal of themeBCR is to ... the

## Installation

You can install the development version of themeBCR from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("ClassicCK/themeBCR")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example, echo = F}
library(themeBCR)
library(ggplot2)
library(cutr)

lm_eqn <- function(df, y, x){
  formula = as.formula(sprintf('%s ~ %s', y, x))
  m <- lm(formula, data=df);
  # formating the values into a summary string to print out
  # ~ give some space, but equal size and comma need to be quoted
  eq <- substitute(italic(target) == a + b %.% italic(input)*","~~italic(r)^2~"="~r2*","~~p~"="~italic(pvalue), 
                   list(target = y,
                        input = x,
                        a = format(as.vector(coef(m)[1]), digits = 2), 
                        b = format(as.vector(coef(m)[2]), digits = 2), 
                        r2 = format(summary(m)$r.squared, digits = 3),
                        # getting the pvalue is painful
                        pvalue = format(summary(m)$coefficients[2,'Pr(>|t|)'], digits=1)
                   )
  )
  as.character(as.expression(eq));                 
}

wingspan <- read.csv("/Users/christopher/Library/Mobile Documents/com~apple~CloudDocs/wingspan/Birds-Table 1.csv")
popularity <- read.csv("/Users/christopher/Library/Mobile Documents/com~apple~CloudDocs/popularity/covariates and results-Table 1.csv")
colnames(popularity)[2] <- "Scientific.name"

data <- merge(wingspan, popularity)
data$Habitat <- gsub("Grasslands", "Grassland", data$Habitat)
data$Wingspan <- smart_cut(data$Wingspan, 5, "groups")
data$`Wingspan (cm)` <- data$Wingspan
```

```{r pressure}
ggplot(data, aes(x = Victory.points, y = popularity, alpha = 0.2)) +
   geom_point(aes(color = Habitat, size = `Wingspan (cm)`)) +
   geom_smooth(method = "glm", se = TRUE, colour = '#3C3C3C') +
   themeBCR() +
   scale_fill_BCR(palette = "Wingspan") +
   labs(caption = "SOURCES: Wingspan, Schuetz & Johnston 2019 \n© 2023 Christopher L. Kilner, PhD",
        title = "Do Birds of a Feather Flock Together?",
        subtitle = "Bird popularity score versus Wingspan point values by species") +
   scale_alpha(guide = FALSE) +
   ylab("Popularity") +
   xlab("Wingspan Victory Points") +
   geom_label(
     data = data[data$popularity > 3 | data$popularity < -1.3 | data$Common.name == "Baltimore Oriole",],
     aes(x = Victory.points, y = popularity, color = Habitat, label = Common.name),
     fill = "white",
     size = 3,
     fontface = "bold",
     hjust = 1.151,
     label.size = NA, 
     alpha = 1,
     show.legend  = F)
```
